// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateScript(arg1) {
  return window['go']['main']['App']['CreateScript'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetLatestLog(arg1) {
  return window['go']['main']['App']['GetLatestLog'](arg1);
}

export function GetRunDetail(arg1) {
  return window['go']['main']['App']['GetRunDetail'](arg1);
}

export function GetRunHistory(arg1) {
  return window['go']['main']['App']['GetRunHistory'](arg1);
}

export function GetRunningScripts() {
  return window['go']['main']['App']['GetRunningScripts']();
}

export function GetScheduleOverview() {
  return window['go']['main']['App']['GetScheduleOverview']();
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetScriptsByCategory(arg1) {
  return window['go']['main']['App']['GetScriptsByCategory'](arg1);
}

export function InferFromScriptPath(arg1) {
  return window['go']['main']['App']['InferFromScriptPath'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenInVSCode(arg1) {
  return window['go']['main']['App']['OpenInVSCode'](arg1);
}

export function RunScript(arg1, arg2) {
  return window['go']['main']['App']['RunScript'](arg1, arg2);
}

export function SaveGlobalConfig(arg1) {
  return window['go']['main']['App']['SaveGlobalConfig'](arg1);
}

export function SaveSchedule(arg1) {
  return window['go']['main']['App']['SaveSchedule'](arg1);
}

export function StopScript(arg1) {
  return window['go']['main']['App']['StopScript'](arg1);
}

export function ToggleSchedule(arg1, arg2) {
  return window['go']['main']['App']['ToggleSchedule'](arg1, arg2);
}

export function UpdateScript(arg1) {
  return window['go']['main']['App']['UpdateScript'](arg1);
}
